stages:
  - testes
  - build

variables:
  IMAGE_TAG: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_NAME}
  IMAGE_TAG_RELEASE: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}

test:
  stage: test
  image: centos:7
  tags:
    - linux-runner
  before_script:
    - apt-get update
    - apt-get install -y yamllint
    - python -m pip install --upgrade pip && python -m pip install -r requirements-dev.txt

  script:
    - py.test tests/

.login:
  stage: build
  image: docker:stable
  services:
    - docker:19.03.0-dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
  before_script:
    - echo $CI_REGISTRY_PASSWORD | docker login --password-stdin -u $CI_REGISTRY_USER gitlab.com
    - |-
      [[ -z "${DOCKER_HUB_USER}" ]] &&
      echo "docker hub credentials are not set (using anonymous)" ||
      (echo $DOCKER_HUB_PASSWORD | docker login --password-stdin -u $DOCKER_HUB_USER)
    - docker pull $DOCKER_IMAGE_TAG_LATEST || true

.build:
  extends: .login
  script:
    - docker build --build-arg ACCESS_TOKEN=$ACCESS_TOKEN --cache-from $IMAGE_TAG_LATEST -t $IMAGE_TAG$ARCH_SUFFIX .
    - docker push $IMAGE_TAG$ARCH_SUFFIX

build_on_push_x86:
  extends: .build
  variables:
    ARCH_SUFFIX: -x86
  except:
    - master
    - tags
  tags:
    - docker-linux

build_on_push_arm64:
  extends: .build
  variables:
    ARCH_SUFFIX: -arm64
  except:
    - master
    - tags
  tags:
    - docker-jetson

build_on_release_x86:
  extends: .build
  variables:
    ARCH_SUFFIX: -x86
    IMAGE_TAG_RELEASE: $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
  only:
    - tags
  after_script:
    - docker tag ${IMAGE_TAG}$ARCH_SUFFIX ${IMAGE_TAG_RELEASE}$ARCH_SUFFIX
    - docker push ${IMAGE_TAG_RELEASE}$ARCH_SUFFIX
  tags: 
    - docker-linux

build_on_release_arm64:
  extends: .build
  variables:
    ARCH_SUFFIX: -arm64
    IMAGE_TAG_RELEASE: $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
  only:
    - tags
  after_script:
    - docker tag ${IMAGE_TAG}$ARCH_SUFFIX ${IMAGE_TAG_RELEASE}$ARCH_SUFFIX
    - docker push ${IMAGE_TAG_RELEASE}$ARCH_SUFFIX
  tags:
     - docker-jetson
